#!/bin/sh -x

# This sets up my(!) development environment. 
# It may work for you, or it may not.
#
# !!! USE AT YOUR OWN RISK !!!
#
# Markus Juenemann

THISDIR=`pwd`

yum -y install http://mirror.rackcentral.com.au/epel/6/i386/epel-release-6-8.noarch.rpm 
yum -y install vim-enhanced git wget bzip2 tar python-devel perl-devel ccache \
               ipython python-argparse pylint gitflow man expect socat tcpdump
yum -y groupinstall 'Development tools' 
yum -y localinstall expect-lite-4.8.1.noarch.rpm 
yum -y localinstall filepp-1.8.1-1.noarch.rpm 
yum -y update

[ -f /usr/local/bin/gcc ] || ln -s `which ccache` /usr/local/bin/gcc
[ -f /usr/local/bin/g++ ] || ln -s `which ccache` /usr/local/bin/g++
[ -f /usr/local/bin/cc  ] || ln -s `which ccache` /usr/local/bin/cc
[ -f /usr/local/bin/c++ ] || ln -s `which ccache` /usr/local/bin/c++

cd /usr/local/src

[ -d /usr/local/src/redis-collectd-plugin.git ] || mkdir /usr/local/src/redis-collectd-plugin.git
git clone https://github.com/powdahound/redis-collectd-plugin.git /usr/local/src/redis-collectd-plugin.git

[ -d /usr/local/src/collectd.git ]] || mkdir /usr/local/src/collectd.git
git clone git clone https://github.com/collectd/collectd.git /usr/local/src/collectd.git


# Install various collectd versions
#
cd /usr/local/src
for v in 5.4.2 5.4.1 5.4.0 5.3.2 5.3.0 5.2.2; do
#for v in 5.4.2; do
    [ -d /opt/collectd-$v ] && rm -rfv /opt/collectd-$v
    cd /usr/local/src
    [ -f collectd-$v.tar.bz2 ] || wget https://collectd.org/files/collectd-$v.tar.bz2
    tar xvfj collectd-$v.tar.bz2
    cd collectd-$v
    ./configure --prefix=/opt/collectd-$v --with-python --config-cache --enable-debug
    make install

    cd $THISDIR ; pwd
    filepp -DVERSION=$v collectd.conf.in > /opt/collectd-$v/etc/collectd.conf
    /opt/collectd-$v/sbin/collectd -t || exit 1
    /opt/collectd-$v/sbin/collectd -T || exit 1
done
  


